<a href="https://www.kaggle.com/code/gpreda/sanity-test-for-medqaro?scriptVersionId=299449706" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

# Introduction

Quick test for the dataset.

We will use this dataset to create a Kaggle Benchmark.
See here for more details: [MedQARo - Benchmark for Medical Q and A in Romanian](https://www.kaggle.com/benchmarks/gpreda/medqaro-benchmark-for-medical-q-and-a-in-romanian).

The MedQARo: A Large-Scale Benchmark for Medical Question Answering in Romanian (on Kaggle: https://www.kaggle.com/datasets/gpreda/medqaro-benchmark-for-medical-q-and-a-in-romanian) dataset is used to create the tests in the tasks.

In this Notebook we quikly glimpse the dataset.

In [1]:
import numpy as np
import pandas as pd
import json
import tiktoken


import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/medqaro-benchmark-for-medical-q-and-a-in-romanian/romedqa_val_dataset.csv
/kaggle/input/medqaro-benchmark-for-medical-q-and-a-in-romanian/romedqa_test_dataset.csv
/kaggle/input/medqaro-benchmark-for-medical-q-and-a-in-romanian/romedqa_train_dataset.csv
/kaggle/input/medqaro-benchmark-for-medical-q-and-a-in-romanian/cross_center_cross_diagnosis.csv

We will use the validation set.

In [2]:
val_df = pd.read_csv("/kaggle/input/medqaro-benchmark-for-medical-q-and-a-in-romanian/romedqa_val_dataset.csv")

# Glimpse the data

In [3]:
val_df.shape

(15328, 4)

In [4]:
val_df.head(2)

,Unnamed: 0,Epicriza,Intrebare,Raspuns
0,0,Neoplasm mamar drept neglijat diagnostic si te...,Care este tipul chimioterapiei aplicate acestu...,3.0
1,1,Neoplasm mamar stang operat (mastectomie radic...,Unde s-au răspândit metastazele la această pac...,0

# Statistics

## Length of texts

Let's check the length of texts in this dataset.

In [5]:
val_df.columns

Index(['Unnamed: 0', 'Epicriza', 'Intrebare', 'Raspuns'], dtype='object')

In [6]:
for col in ['Epicriza', 'Intrebare', 'Raspuns']:
    val_df[f"text_length_{col}"] = val_df[col].str.len()

## Number of words

And let's check the number of words.

In [7]:
for col in ['Epicriza', 'Intrebare', 'Raspuns']:
    val_df[f"word_count_{col}"] = val_df[col].str.split().str.len()

## Number of tokens

And then let's check the number of tokens.

In [8]:
encoding = tiktoken.get_encoding("cl100k_base")

for col in ['Epicriza', 'Intrebare', 'Raspuns']:
    val_df[f"token_count_{col}"] = val_df[col].apply(lambda x: len(encoding.encode(str(x))))

## Summary statistics values

Now, let's calculate few stats. We will apply `describe` to the values that we just calculated, to generate the count, min, max, mean, std, and the other values of descriptive statistics.

In [9]:
val_df.columns

Index(['Unnamed: 0', 'Epicriza', 'Intrebare', 'Raspuns',
       'text_length_Epicriza', 'text_length_Intrebare', 'text_length_Raspuns',
       'word_count_Epicriza', 'word_count_Intrebare', 'word_count_Raspuns',
       'token_count_Epicriza', 'token_count_Intrebare', 'token_count_Raspuns'],
      dtype='object')

In [10]:
sel_columns = ['text_length_Epicriza', 'text_length_Intrebare', 'text_length_Raspuns',
       'word_count_Epicriza', 'word_count_Intrebare', 'word_count_Raspuns',
       'token_count_Epicriza', 'token_count_Intrebare', 'token_count_Raspuns']

In [11]:
val_df[sel_columns].head()

,text_length_Epicriza,text_length_Intrebare,text_length_Raspuns,word_count_Epicriza,word_count_Intrebare,word_count_Raspuns,token_count_Epicriza,token_count_Intrebare,token_count_Raspuns
0,53890,92,3,7554,11,1,19337,29,3
1,10341,52,1,1314,7,1,3779,20,1
2,15163,63,10,2201,8,3,5668,16,4
3,20842,43,2,2957,6,1,7585,14,1
4,14674,66,5,2208,9,1,5562,20,3

In [12]:
stats = []
for col in sel_columns:
    stats.append((col, val_df[col].describe().to_json()))

Let's put now the data in a pandas DataFrame.

In [13]:
rows = []
for name, stats_json in stats:
    stats_dict = json.loads(stats_json)
    stats_dict["metric"] = name
    rows.append(stats_dict)

stats_df = pd.DataFrame(rows)

stats_df = stats_df.set_index("metric")

Let's round the values to 2 decimals, for easier readability.

In [14]:
# Convert numeric columns
for col in stats_df.columns:
    stats_df[col] = stats_df[col].round(2)   # keep 2 decimals

It is much easier to see the results if be transpose this DataFrame.

In [15]:
stats_df.T

metric,text_length_Epicriza,text_length_Intrebare,text_length_Raspuns,word_count_Epicriza,word_count_Intrebare,word_count_Raspuns,token_count_Epicriza,token_count_Intrebare,token_count_Raspuns
count,15328.00,15328.00,15328.00,15328.00,15328.00,15328.00,15328.00,15328.00,15328.00
mean,21356.46,63.72,9.21,2916.09,9.10,1.95,7671.06,19.78,4.44
std,12363.61,17.16,42.07,1681.75,2.55,6.26,4431.37,5.51,18.10
min,2425.00,18.00,1.00,332.00,2.00,1.00,855.00,6.00,1.00
25%,11479.00,52.00,2.00,1623.00,7.00,1.00,4210.00,16.00,1.00
50%,19766.00,64.00,3.00,2676.00,9.00,1.00,7066.00,20.00,2.00
75%,27947.00,75.00,7.00,3735.00,11.00,1.00,9796.00,23.00,3.00
max,66139.00,129.00,969.00,9483.00,18.00,150.00,27848.00,37.00,408.00

The rationale of this investigation is to have a intuition of the overall token use when we will run tasks to evaluate the capacity of various LLMs to answer correctly to the questions about the epicrisis. The ground truth is in the expected answer, also present in the dataset.

That's all for now.   

Check the Benchmark results here: [MedQARo: Benchmark for Medical Q&A in Romanian](https://www.kaggle.com/benchmarks/gpreda/medqaro-benchmark-for-medical-q-and-a-in-romanian)